name       : perl-sdl
version    : 2.548
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/F/FR/FROGGS/SDL-2.548.tar.gz : 252a192bfa9c2070a4883707d139c3a45d9c4518ccd66a1e699b5b7959bd4fb5
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Simple DirectMedia Layer for Perl
description: |
    Package of modules that provide both functional and object oriented interfaces to the Simple DirectMedia Layer for Perl. This package takes some liberties with the SDL API, and attempts to adhere to the spirit of both the SDL and Perl.
builddeps  :
    - pkgconfig(SDL_Pango)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_ttf)
    - perl-alien-sdl
    - perl-module-build
    - perl-test-most
    - perl-tie-simple
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
#check      : |
#    perl Build test
